# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 935d8a38dc705177eb352621e1695452b0a3ec0a8902c4498ca90e81f12bf7d5be58321a26b0cc63b93ba82f9bf9c56231c0d25d7882d0d68a494d6aded1a90d

test:
  secret_key_base: 1cd75eca910639eaf67f21932223d65a839bb414dc1b87b844390ff3e993a28cbd6dfe6607f3be0ac6923e14f369236e4233c76ac2a561313903359e00b1b161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
